### ISSUE TITLE
Symlink issue

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#1]
I am on branch mpc-wpts, but this issue was occurring on the main branch as well, from what I can remember. This only occurs when building with --symlink-install. Otherwise, everything seems to work fine. The build goes fine in both cases, but this is the output from trying to run the simulation launch files after building with symlink. This hasn't been tested on the real vehicle.

[symlink_output.txt](https://github.com/uwsbel/autonomy-research-testbed/files/12344030/symlink_output.txt)

**Comment by AaronYoung5** [comment]
You'll need to source the `setup.bash` after a rebuild using `--symlink-install`. You should only need to do this after the first rebuild using `--symlink-install`.
