### ISSUE TITLE
Reorganize a-alg structure.

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#105]
Rather than only having one instance of each algorithm, have a folder of algorithms to choose from.

**Comment by StefanCaldararu** [comment]
This definitely makes sense for path planning and control. Don't think this makes sense for state estimation (will elaborate more), and unsure if this is already done for perception?

**Comment by AaronYoung5** [comment]
Nice! But in regards to state estimation, there's different types of localization, right? Like SLAM, filtering (of which have multiple; I think this is what you're talking about when you say passing a parameter, right), dead reckoning, visual odometry/optical flow, etc. So I think multiple nodes would make sense here, too. Does that make sense to you or am I seeing things wrong?

**Comment by StefanCaldararu** [comment]
> Nice! But in regards to state estimation, there's different types of localization, right? Like SLAM, filtering (of which have multiple; I think this is what you're talking about when you say passing a parameter, right), dead reckoning, visual odometry/optical flow, etc. So I think multiple nodes would make sense here, too. Does that make sense to you or am I seeing things wrong?

Yeah that makes sense. I see two options (this relates to your comment in the PR as well): 
- Every algorithm has it's own node.
- Nodes are defined based off of the subscribers/publishers, and the task they aim to accomplish. Then, parameters are used to select the specific algorithm. This was my thought for the state estimation. This also relates to your comment on the name for the `cone_path_planner` -> The name of the node aims to define the task. If you want to change the algorithm, but it completes the same task (for this, read a list of cones and determine a target path), then move the algos to a different file (like in State Estimation), and use a parameter. Note: this is NOT the way autoware does it.

Thoughts on this? I have a slight preference for 2, but no strong opinion. If you have a strong preference for 1, then we can go with that.

**Comment by AaronYoung5** [comment]
Ya I see option 1 as the best. The input outputs should be \~similar\~ between each organizational subfolder. I believe this is how autoware does it, correct?

I don't think task specific packages make the most sense because `cone_path_planner` isn't specific to cones, it just takes objects of different type describing left and right bounds for a path and tries to contorl through it (the objects could be dashed lines, walls, etc.). I'm confused by what you mean "move the algos to a different file"?

**Comment by StefanCaldararu** [comment]
> Ya I see option 1 as the best. The input outputs should be ~similar~ between each organizational subfolder. I believe this is how autoware does it, correct?

Yeah that's the way autoware does it, from what I see.

> I don't think task specific packages make the most sense because `cone_path_planner` isn't specific to cones, it just takes objects of different type describing left and right bounds for a path and tries to contorl through it (the objects could be dashed lines, walls, etc.). I'm confused by what you mean "move the algos to a different file"?

I guess I see what you mean... See the current organization of the State Estimation Node. Because `Extended Kalman Filter

**Comment by AaronYoung5** [comment]
Ya any solution will have drawbacks, and I think this is one of them. Ideally, it should be implemented as a filter graph (like ch sensor or `ffmpeg`) where the outputs of a node must match of the inputs of the nodes which feed into it. Idk if this is possible in ROS, but the easiest way to facilitate this is by documenting the input and outptus in the readme of that node and then just ensuring the launch files are setup correctly that the graph makes sense. I think this is fine cause that's what we do now.

Related to state estimation, I think consistency is important, but I understand what you're saying. I guess if we don't want to change the code, it could be `state_filtering` or something like that to encompass both. But also, why do we need both algos?

**Comment by AaronYoung5** [comment]
Also I talked with Dan, and he said that from now on, everytime you hit the close with comment button by accident, you owe me a dollar

**Comment by StefanCaldararu** [comment]
@AaronYoung5 I'm a little unsure of the best way to deal with the launchfiles, so that they can launch various "state_estimation" packages easily. Should each package have it's own launchfile? They will sometimes have different parameters / subs / pubs, what's the best way to go about this?

**Comment by AaronYoung5** [comment]
Ya I think take insipration from the `art_sensing` or `art_vehicle` folder. Like a common `art_localization.launch.py` file which includes all the other launch files.
