### ISSUE TITLE
When a-stack fails nodes don't get shut down correctly

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#106]
@AaronYoung5 Some python processes get left running when nodes fail in the a-stack. How to reproduce: got into the launch file of the path planning node (`workspace/src/common/launch/art_planning_launch/launch/art_planning.launch.py`), and change the `package`, `executable`, and  `name` so that the path planning node can't be found anymore. Run the a-stack with sim & vis, and you'll see that the cone detection node is still running. Can confirm with htop as well.

@harryzhang1018 This was the issue we were seeing on the Jetson.

**Comment by AaronYoung5** [comment]
Ya unfortunately I don't think there's a ros-esque solution to this. Maybe you'll find different info, but it seems like there is no solution this on the ROS 2 forums (other than killing the processes directly using `kill`).

I have two thoughts:
- Maybe there is something specific about our setup that means these nodes don't get killed correctly. Maybe try running minimal examples (i.e. 1 launch file, 1 node) and then work up towards more complicated setups (if you can't replicate the issue). My guess would be there's nothing specific about our setup that causes this, but not sure.
- We can make nodes lifecycle nodes which I _think_ have a cleaner shutdown mechanism, but I don't know enough about lifecycle nodes right now.

**Comment by StefanCaldararu** [comment]
Sounds good. This only seems to be an issue when packages aren't found and so the whole launch fails. If a package just fails and the rest of the launch proceeds, then you can `ctrl+ C` the launch and everything shuts down fine. Closing bcs this seems to be a ros issue
