### ISSUE TITLE
building `oak` or `art5` fails on lab machine

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#122]
@AaronYoung5 Title, fails when it checks OS of the image I think? 
- Is this still an issue we should worry about given your new PR? Haven't gotten a chance to look at it closely.
- should this be able to build on systems other than the Jetson?

here is what. I see: 
<img width="717" alt="image" src="https://github.com/uwsbel/autonomy-research-testbed/assets/52421529/c67c4825-d58d-42fb-8b46-e3e0caacf41e">

**Comment by AaronYoung5** [comment]
Your lab workstation is probs x86, but the image which `oak` and `art5` build on is for jetson (aarch). So you can't build those images on your workstation. That's the point of `dev`.
