### ISSUE TITLE
ROS demos doesn't work in art-chrono container when building the container from dockerfile

### ISSUE THREAD

**Issue by harryzhang1018** [uwsbel/autonomy-research-testbed#137]
@AaronYoung5 

So I am on master branch and I tried to build art-chrono using the following: `atk dev -bua -s chrono --optionals gpus vnc`. Before I built it, I already tried `docker system prune -a`. 

After getting into container, I tried to run demo and got the following error:
![image](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/a123c9b5-079d-4f98-a009-1c1041e01665)

I also tried to build cpp demo, and get the following error:
![image](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/ed7a1132-399c-434f-960d-7278c5286b53)

**Comment by StefanCaldararu** [comment]
Likely not the same issue bcs my build had finished, but I've seen a similar issue with both chrono::ros and chrono::sensor, fix was to downgrade numpy to 1.24 - but this as after my chrono build finished so I'm assuming this is a dfiferent issue
