### ISSUE TITLE
Multiple publishers to /Vehicle_State and /VehicleState

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#17]
This is present in Launch Rework, including in commit #62edf9a (the last commit by @AaronYoung5). There seem to be 5 publishers to /vehicle/state and 3 publishers to /vehicle_state. I am checking if this is true as of earlier build versions, but I don't remember this being an issue. Will update as progress is made with diagnosis. If changes are made to #10 they should be pushed further to #16.

**Comment by AaronYoung5** [comment]
Ya, and they have an unused callback. This should increase network usage, as well. We should delete this code if it's not necessary in these nodes.

https://github.com/uwsbel/autonomy-research-testbed/pull/10/files#diff-e4da91088671bf52d705867ad69c7bd2887a5227e4301167121e62ede6ef5115R100

**Comment by AaronYoung5** [comment]
You can create a PR with a fix, and we can merge before everything else, and then we do a [`git rebase`](https://git-scm.com/docs/git-rebase).

**Comment by StefanCaldararu** [comment]
Issue fixed #19
