### ISSUE TITLE
Errors when launch the simulation

### ISSUE THREAD

**Issue by harryzhang1018** [uwsbel/autonomy-research-testbed#22]
When I pull the main branch, I can set up containers fine, but I got the following error:
![Screenshot from 2023-08-31 12-29-02](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/701f8529-382a-4b0a-a283-026e6cce75c5)

I think up till building onnx file it's fine, but the next error shouldn't happen.

[ERROR] [yolov5_detector-1]: process has died [pid 12495, exit code 1, cmd '/home/art/art/workspace/install/cone_detector/lib/cone_detector/yolov5_detector --ros-args -r __node:=yolov5_detector --params-file /tmp/launch_params_haef116x --params-file /tmp/launch_params_86w76es2 --params-file /tmp/launch_params__ox74mjw --params-file /tmp/launch_params_l63cgae0 -r ~/input/image:=/sensing/front_facing_camera/raw -r ~/input/vehicle_state:=/vehicle/state -r ~/output/objects:=/perception/objects'].

**Comment by AaronYoung5** [comment]
In reference to #10.

What command did you run?

**Comment by AaronYoung5** [comment]
@harryzhang1018 And did you rebuild the container after pulling and everything? And you reran colcon build and resourced the install file?

**Comment by harryzhang1018** [comment]
@AaronYoung5, I think this error could be solved by deleting all related docker images and containers and doing a fresh rebuild.
