### ISSUE TITLE
Optix 7.7

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#26]
Chrono now requires optix 7.7.0

**Comment by harryzhang1018** [comment]
@StefanCaldararu I tried to replace all "7.5" to "7.7" in chrono.dockerfile and it works for me. @AaronYoung5 is this looking good to you? 
![Screenshot from 2023-09-07 15-09-01](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/3b1d09f4-ab8b-471c-813a-5d1c9919b33d)

**Comment by AaronYoung5** [comment]
Ya, fine by me. I'll let Stefan approve. I have a future PR that changes the version component to be in the atk.yml as a build argument.
