### ISSUE TITLE
Colcon build fails

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#27]
@AaronYoung5 I believe this has something to do with moving the nmea and bluespace packages into the sensing subfolder, but I am not sure... When I removed the directories from the src folder I can no longer run colcon build. I get the following error message, unclear to me what the actual cause of this is...
[error.txt](https://github.com/uwsbel/autonomy-research-testbed/files/12553260/error.txt)

@harryzhang1018 was able to recreate this issue by checking out the master branch, and I get these issues from a fresh build (recloned the repo, cleared my docker cache).

**Comment by AaronYoung5** [comment]
so no `build`, `install`, and `log` directories?

**Comment by StefanCaldararu** [comment]
> so no `build`, `install`, and `log` directories?

If you're asking if I removed these directories and tried rebuilding, that is correct I did remove them and try rebuilding from scratch. I have also tried removing container images, and even deleting the entire ART repo and re cloning.

If you're asking if the directories get created, they do and they seem to get populated but multiple packages seem to fail, and the rest get aborted. `arduino_driver` and `launch_utils` fail, and the rest get aborted.

**Comment by AaronYoung5** [comment]
What if you run `cd src/sensing/bluespace_ai_xsens_ros_mti_driver/lib/xspublic && make && cd -`. I can't replicate the issue.

**Comment by harryzhang1018** [comment]
> What if you run `cd src/sensing/bluespace_ai_xsens_ros_mti_driver/lib/xspublic && make && cd -`. I can't replicate the issue.

@AaronYoung5   That's a bluespace_xsens issue, but I think for here, `colcon build` failed even before that, it fails on the step of building rosboard which I never seen before.

**Comment by AaronYoung5** [comment]
Ya, I think you're right. I'm rebuilding from scratch.

**Comment by harryzhang1018** [comment]
> What if you run `cd src/sensing/bluespace_ai_xsens_ros_mti_driver/lib/xspublic && make && cd -`. I can't replicate the issue.

@AaronYoung5   That's a bluespace_xsens issue, but I think for here, `colcon build` failed even before that, it fails on the step of building rosboard which I never seen before.

**Comment by StefanCaldararu** [comment]
Problem is with setuptools. Fix (for now) is `pip3 install setuptools==68.1.2`

**Comment by AaronYoung5** [comment]
I believe this is fixed with `68.2.2`. Going to close. Can reopen if needed.
