### ISSUE TITLE
Can't echo custom message types.

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#31]
@AaronYoung5 with `ros2 topic echo /vehicle/state` I get the following error message: 

`The message type 'chrono_ros_msgs/msg/ChVehicle' is invalid`

I would also like to reopen a discussion which I believe we had briefly about using standard ros message types - are there any messages we have that wouldn't fit?

**Comment by AaronYoung5** [comment]
Where are you running it? Shouldn't be getting that error if you're in the workspace that has `chronO-ros_msgs` built.

But I'm open to the stand ros message types. We also have `art_msgs`, do you think we should get rid of those, too?
