### ISSUE TITLE
Colcon build fails - Permission denied

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#46]
@AaronYoung5 Working on a fresh machine (just installed docker, docker compose, atk). Colcon build is failing due to some permission issues... wondering if I missed something in the Docker setup. I get the following error when running `colcon build` in the dev container: 

`Traceback (most recent call last):
  File "/usr/bin/colcon", line 33, in <module>
    sys.exit(load_entry_point('colcon-core==0.15.0', 'console_scripts', 'colcon')())
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 118, in main
    return _main(command_name=command_name, argv=argv)
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 185, in _main
    create_log_path(args.verb_name)
  File "/usr/lib/python3/dist-packages/colcon_core/location.py", line 186, in create_log_path
    os.makedirs(str(path))
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'log/build_2023-11-02_13-32-30' `

Versions of everything: 
Docker: 24.0.5
Docker compose: 2.21.0
atk: 2.0.11
Runing on Ubuntu 22.04.3
Nvidia Drivers: 545.23.06

**Comment by AaronYoung5** [comment]
Can you run `id -u` and `id -g` on the host?

**Comment by StefanCaldararu** [comment]
> Can you run `id -u` and `id -g` on the host?

both return 1002 on the host and 1000 in the dev container

**Comment by AaronYoung5** [comment]
The default user in linux has a uid and gid of 1000 + the index of the user on the system. So in your case, sounds like there were already 2 other users, so your uid/gid is 1002. You're going to need to rebuild the container and pass in the new uid/gid ([which defaults to 1000](https://github.com/uwsbel/autonomy-research-testbed/blob/32dffef5502b45fcd9e1ddb4931d468f94b04c42/atk.yml#L38)). 

To update you have two options:
1. Add `USER_UID` and `USER_GID` to the `.env` with your `gid` and `uid`. `.env` is ignored in git, so no worries there.
> ```
> # .env
> USER_UID=1002
> USER_GID=1002
> ```
2. Export them as environment variables in your profile
> ```
> # bashrc/zshrc/profile
> export USER_UID=1002
> export USER_GID=1002
> ```

**Comment by StefanCaldararu** [comment]
This worked, thanks! Leaving this open so you can document this somewhere else as well.

**Comment by StefanCaldararu** [comment]
@AaronYoung5 can I close this now that we merged docs in?

**Comment by AaronYoung5** [comment]
See [FAQs](https://github.com/uwsbel/autonomy-research-testbed/blob/master/docs/misc/faq.md#file-permissions).
