### ISSUE TITLE
Bugs in main branch...

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#49]
@AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.).  Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error: 

`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`

any ideas?

**Comment by AaronYoung5** [comment]
> @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> 
> `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> 
> any ideas?

In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.

**Comment by AaronYoung5** [comment]
And @harryzhang1018 why do you think the container breaks the nvidia drivers lol

**Comment by StefanCaldararu** [comment]
> > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > any ideas?
> 
> In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.

ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...

Last error that is still coming up: 
'[state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.'

**Comment by StefanCaldararu** [comment]
> And @harryzhang1018 why do you think the container breaks the nvidia drivers lol

he tried running the python simulations, and then noticed his nvidia drivers weren't working correctly. Then tried rebooting and computer wont reboot XD

**Comment by AaronYoung5** [comment]
> > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > any ideas?
> > 
> > 
> > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> 
> ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> 
> Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`

You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.

**Comment by AaronYoung5** [comment]
> > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > any ideas?
> > > 
> > > 
> > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > 
> > 
> > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> 
> You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.

What command are you running @StefanCaldararu ?

**Comment by StefanCaldararu** [comment]
> > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > any ideas?
> > > 
> > > 
> > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > 
> > 
> > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> 
> You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.

do I need to rebuild the container for this? doesn't work for me...

**Comment by AaronYoung5** [comment]
> > > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > > any ideas?
> > > > 
> > > > 
> > > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > > 
> > > 
> > > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> > 
> > 
> > You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.
> 
> do I need to rebuild the container for this? doesn't work for me...

tear down and start up. `atk dev -dua ...`

**Comment by StefanCaldararu** [comment]
> > > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > > any ideas?
> > > > 
> > > > 
> > > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > > 
> > > 
> > > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> > 
> > 
> > You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.
> 
> What command are you running @StefanCaldararu ?

`ros2 launch art_launch art.launch.py use_sim:=true vis:=true hostname:=art-chrono`

**Comment by StefanCaldararu** [comment]
> > > > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > > > any ideas?
> > > > > 
> > > > > 
> > > > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > > > 
> > > > 
> > > > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > > > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> > > 
> > > 
> > > You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.
> > 
> > 
> > do I need to rebuild the container for this? doesn't work for me...
> 
> tear down and start up. `atk dev -dua ...`

doesn't seem to help for me...

**Comment by harryzhang1018** [comment]
> And @harryzhang1018 why do you think the container breaks the nvidia drivers lol
@AaronYoung5  @StefanCaldararu 
Clarification: from day one, I knew this is a annoying bug from nvidia, and I have already fixed it lol

**Comment by AaronYoung5** [comment]
> > And @harryzhang1018 why do you think the container breaks the nvidia drivers lol
> > @AaronYoung5  @StefanCaldararu
> Clarification: from day one, I knew this is a annoying bug from nvidia, and I have already fixed it lol

Can you explain more about the bug?

**Comment by AaronYoung5** [comment]
> > > > > > > @AaronYoung5 There seem to be lots of bugs in the main branch (The state estimation import, `chrono_ros_bridge` node still exists, running the container may or may not break nvidia drivers [according to @harryzhang1018], etc.). Right now I am at a point where I _think_ the only issue is an error with plotting in the vnc container. Trying to run the a-stack with a python simulation gives me the following error:
> > > > > > > `ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
> > > > > > > any ideas?
> > > > > > 
> > > > > > 
> > > > > > In `dev` or `chrono` you see this? What is `$DISPLAY`? Should be `vnc:0.0`.
> > > > > 
> > > > > 
> > > > > ok I had to set the `$DISPLAY` variable manually and now it works; I think I had this issue a while ago but don't remember what the correct solution was...
> > > > > Last error that is still coming up: ` [state_estimation-2] TypeError: The given value is not one of the allowed types 'EstimationAlgorithmOption.GROUND_TRUTH'.`
> > > > 
> > > > 
> > > > You can use `--optionals vnc` to do the display thing. And not sure about the GROUND_TRUTH thing, will look into it.
> > > 
> > > 
> > > do I need to rebuild the container for this? doesn't work for me...
> > 
> > 
> > tear down and start up. `atk dev -dua ...`
> 
> doesn't seem to help for me...

:( I'll try myself tn

**Comment by harryzhang1018** [comment]
> > > And @harryzhang1018 why do you think the container breaks the nvidia drivers lol
> > > @AaronYoung5  @StefanCaldararu
> > > Clarification: from day one, I knew this is a annoying bug from nvidia, and I have already fixed it lol
> 
> @harryzhang1018 Can you explain more about the bug?

nvidia-driver-535 stop working becuase some packages broken, Huzaifa saw the same issue, once we did fix broken package through apt, it works again.

**Comment by AaronYoung5** [comment]
Closing after #51 was merged.
