### ISSUE TITLE
Vehicle falls apart

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#54]
@harryzhang1018 title. Vehicle seems to fall apart in the main branch (after #49 gets resolved and #51 gets merged), when using the python sim. @AaronYoung5 thinks this has to do with the control node, any ideas?

**Comment by harryzhang1018** [comment]
@StefanCaldararu  @AaronYoung5 

Hey guys, I am able to reproduce the bug in chrono main branch by setting up alternative steering command of -1 and 1, for example, at each time step, steering respectively equals to (1, 1, 1, 1, -1, 1, 1, 1,..). So I think this is a bug regarding Chrono::Vehicle::ARTcar.

![image](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/27215624-1ede-4c69-afb7-746de6c0520b)

**Comment by AaronYoung5** [comment]
Is the solution then to have a layer between control commands and the vehicle? I believe this should be the case anyways.

**Comment by harryzhang1018** [comment]
> Is the solution then to have a layer between control commands and the vehicle? I believe this should be the case anyways.

@AaronYoung5 I agree the solution should be the "clip" layer of steering command changing rate between vehicle and command, something like:
`if (d_steering < max_d_steering) {steering = steering}
else {steering = steering +\- max_d_steering}`

But I would say it should be inside chrono, cuz ART may not be the only place the Chrono::Vehicle::ARTcar get used. 
Thoughts?

**Comment by AaronYoung5** [comment]
> > Is the solution then to have a layer between control commands and the vehicle? I believe this should be the case anyways.
> 
> @AaronYoung5 I agree the solution should be the "clip" layer of steering command changing rate between vehicle and command, something like: `if (d_steering < max_d_steering) {steering = steering} else {steering = steering +\- max_d_steering}`
> 
> But I would say it should be inside chrono, cuz ART may not be the only place the Chrono::Vehicle::ARTcar get used. Thoughts?

Other chrono vehicles can "achieve" any steering input that's passed to it, we should keep this the same. So I think the clipping should happen on the control side or maybe some intermediate node.

**Comment by harryzhang1018** [comment]
> > > Is the solution then to have a layer between control commands and the vehicle? I believe this should be the case anyways.
> > 
> > 
> > @AaronYoung5 I agree the solution should be the "clip" layer of steering command changing rate between vehicle and command, something like: `if (d_steering < max_d_steering) {steering = steering} else {steering = steering +\- max_d_steering}`
> > But I would say it should be inside chrono, cuz ART may not be the only place the Chrono::Vehicle::ARTcar get used. Thoughts?
> 
> Other chrono vehicles can "achieve" any steering input that's passed to it, we should keep this the same. So I think the clipping should happen on the control side or maybe some intermediate node.

Ummm I see what you mean here. It's prob hard to set up clipping constraint on the driver input for all other vehicles in chrono. 
Then we should write this clipping constraint in control node probably.

**Comment by StefanCaldararu** [comment]
Fixed by #62
