### ISSUE TITLE
State message type

### ISSUE THREAD

**Issue by StefanCaldararu** [uwsbel/autonomy-research-testbed#70]
Currently the `NavSatFix` message type uses quaternions for the orientation of the vehicle. Right now we are just passing the heading (no other orientation info for the vehicle). We are doing this by writing to the "quaternion z" variable, which means we end up leaving a bunch of other variables empty. We also leave all of the covariance variables empty because those aren't used anywhere later in the pipeline, and some of our filters don't generate that data. I see three options for how to go about this: 

- Write a custom vehicle state message type that doesn't include the unnecessary info. This is the most "data efficient" solution, but we would have to switch message types if we want to add the old info back in in the future.
- Translate the heading angle to a quaternion. This generates a lot of unnecessary data (could pass this message with one float, but instead doing it with 4). This is not actually that bad for us, but just not the best practice in general...
- Leave it as is, and if we have an application in the future that requires quaternions or can publish the covariances, do so. This still passes the "large" message types though...

I am leaning towards 3), but wanted to write this out somewhere because @AaronYoung5 commented on it. Thoughts? @harryzhang1018 @ishaanamahajan

**Comment by ishaanamahajan** [comment]
I personally think 3) should work for now, especially since we have 4 different vehicles. Every vehicle would want different data from the message type depending on what application it is being used for.

**Comment by StefanCaldararu** [comment]
Closing bcs ppl didn't reply and I decided we are going with 3.
